project:
  type: book
  output-dir: docs

book:
  title: "Book of Exploratory Data Analysis (EDA)"
  author: "Berk Orbay"
  date: "August 2022"
  chapters:
    - index.qmd
    - part: fundamentals.qmd
      chapters:
        - base-r.qmd
        - base-r-in-detail.qmd
        - dplyr.qmd
        - ggplot2.qmd
        - quarto.qmd
        - shiny.qmd
        - fundamentals-end.qmd
    - part: advanced.qmd
      chapters:
        - reticulate.qmd
        - dplyr-joins.qmd
        - rvest.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



